#! /bin/sh

sxhkd &

bspc config border_width         2
bspc config window_gap           40 

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc config focused_border_color "#ff0000"

bspc config click_to_focus       true

bspc monitor DP-1 -d      
bspc monitor HDMI-0 -d    
bspc monitor DVI-D-0 -d    

#bspc monitor '^1' -s '^3'

#bspc monitor DP-1 -d 1 2 3   
#bspc monitor HDMI-0 -d 4 5 6 
#bspc monitor DVI-D-0 -d 7 8 9 

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
