#!/bin/sh

$XDG_CONFIG_HOME/bspwm/panel_colors

num_mon=$(bspc query -M | wc -l)
 
while read -r line; do
    case $line in
 
        # BSPWM 
      
        W*)
            wm_infos=""
            IFS=':'
            set - ${line#?}
            while [ $# -gt 0 ];do
                item=$1     
                name=${item#?}
                case $item in

					O*)
						# focused occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_FOCUSED_OCCUPIED_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					F*)
						# focused free desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					U*)
						# focused urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
						;;
					o*)
						# occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG} ${name} %{B-}%{F-}"
						;;
					f*)
						# free desktop
						wm_infos="${wm_infos}%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG} ${name} %{B-}%{F-}"
						;;
					u*)
						# urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG} ${name} %{B-}%{F-}"
                                                ;;

                        
                esac 
                shift
            done    
            ;; 

            # Conky

	       
            c*) 
                #cpu=$(cut -c 2- <<< "$line")
		cpu="   ${line#?}   "
            ;;

            t*)
                #temp=$(cut -c 2- <<< "$line")
		temp="   ${line#?}   "
            ;;

            r*)
                #root=$(cut -c 2- <<< "$line")
		root="   ${line#?}   "
            ;;

            y*)
                #song=$(cut -c 2- <<< "$line")
		song="   ${line#?}   "
            ;;

            i*)
                #download=$(cut -c 2- <<< "$line")
	        download="   ${line#?}   "
            ;; 

            I*)
                #upload=$(cut -c 2- <<< "$line")
		upload="   ${line#?}   "
            ;;

            v*)
                #volume=$(cut -c 2- <<< "$line")
		volume="   ${line#?}   "
            ;;

            T*)
                #time=$(cut -c 2- <<< "$line")
		time="   ${line#?}   "
            ;;

            D*)
                #date=$(cut -c 2- <<< "$line")
		date="   ${line#?}   "
            ;;  


    esac     

    printf "%s\n" "%{l}${wm_infos} %{c}${song} %{r}${download}${upload}${cpu}${temp}${root}${volume}${date}${time}"

done < <(\
    bspc subscribe & \
    conky -c $XDG_CONFIG_HOME/conky/cpu.conf & \
    conky -c $XDG_CONFIG_HOME/conky/temp.conf & \
    conky -c $XDG_CONFIG_HOME/conky/root.conf & \
    conky -c $XDG_CONFIG_HOME/conky/song.conf & \
    conky -c $XDG_CONFIG_HOME/conky/speedtest-down.conf & \
    conky -c $XDG_CONFIG_HOME/conky/speedtest-up.conf & \
    conky -c $XDG_CONFIG_HOME/conky/time.conf & \
    conky -c $XDG_CONFIG_HOME/conky/date.conf & \
    conky -c $XDG_CONFIG_HOME/conky/volume.conf
) | lemonbar -g 1920x22+1920+0 -p -B $COLOR_BACKGROUND -f FontAwesome-11 -f Roboto-10 -F $COLOR_FOREGROUND
